name: amc_rms
version: 1.0.0+1
publish_to: none
description: Akola Municipal Corporation Revenue Management System.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  dropdown_button2: ^1.9.2
  datetime_picker_formfield: ^2.0.1
  intl: ^0.18.0
  flutter_group_button: ^2.0.1
  image_picker: ^0.8.5
  image_cropper: ^3.0.1
  flutter_image_compress: ^1.1.3
  path: ^1.8.2
  geolocator: ^8.2.0
  permission_handler: ^9.2.0
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  typed_data: ^1.3.1
  print_bluetooth_thermal: ^1.0.5
  esc_pos_utils_plus: ^2.0.1+6
  simple_animations: ^4.1.0
  flutter_screenutil: ^5.7.0
  flutter_spinkit: ^5.2.0
  file_picker: ^4.2.7
  awesome_dialog: ^3.0.2
  expandable_text: ^2.3.0
  expansion_tile_card: ^2.0.0
  pdf: ^3.10.1
  open_file: ^3.2.1
  lottie: ^2.3.2

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: TiroDevanagariMarathi
      fonts:
        - asset: assets/fonts/TiroDevanagariMarathi-Italic.ttf


  uses-material-design: true
