part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const LOGIN_SCREEN = _Paths.LOGIN_SCREEN;
  static const HOME = _Paths.HOME;
  static const FIELD_VERIFICATION_PENDING_LIST = _Paths.FIELD_VERIFICATION_PENDING_LIST;
  static const WATER_HOME_SCREEN = _Paths.WATER_HOME_SCREEN;
  static const TRADE_HOME_SCREEN = _Paths.TRADE_HOME_SCREEN;
  static const ADVERTISEMENT_HOME_SCREEN = _Paths.ADVERTISEMENT_HOME_SCREEN;
  static const PROPERTY_HOME_SCREEN = _Paths.PROPERTY_HOME_SCREEN;
  static const PROPERTY_NEW_ASSESSMENT = _Paths.PROPERTY_NEW_ASSESSMENT;
  static const PROPERTY_CONSESSION = _Paths.PROPERTY_CONSESSION;
  static const WATER_APPLY_CONNECTION = _Paths.WATER_APPLY_CONNECTION;
  static const PROPERTY_MISSING_GEOTAGGING = _Paths.PROPERTY_MISSING_GEOTAGGING;
  static const PROPERTY_WATER_HARVESTING_FIELD_VERIFY = _Paths.PROPERTY_WATER_HARVESTING_FIELD_VERIFY;
  static const GEOTAGGING_VERIFY_FORM = _Paths.FIELD_VERIFICATION_PENDING_LIST + _Paths.GEOTAGGING_VERIFY_FORM;
  static const PAYMENT = _Paths.PAYMENT;
  static const PROPERTY_PAY_PROPERTY_TAX = _Paths.PROPERTY_PAY_PROPERTY_TAX;
  static const HOME_ABOUT = _Paths.HOME_ABOUT;
  static const PROPERTY_SEARCH_ASSESSMENT_DETAIL = _Paths.PROPERTY_SEARCH_ASSESSMENT_DETAIL;
  static const PROPERTY_REPORT = _Paths.PROPERTY_REPORT;
  static const PROPERTY_GB_SAF_APPLY = _Paths.PROPERTY_GB_SAF_APPLY;
  static const PROPERTY_CLUSTER = _Paths.PROPERTY_CLUSTER;
  static const PROPERTY_GB_SAF_VERIFICATION = _Paths.PROPERTY_GB_SAF_VERIFICATION;
  static const SPLASH_SCREEN = _Paths.SPLASH_SCREEN;
  static const PROPERTY_ADD_CLUSTER = _Paths.PROPERTY_ADD_CLUSTER;
  static const PROPERTY_CONCESSION = _Paths.PROPERTY_CONCESSION;
  static const PROPERTY_APPLY_HARVESTING = _Paths.PROPERTY_APPLY_HARVESTING;
  static const PROPERTY_APPLY_FORM_HOME_SCREEN = _Paths.PROPERTY_APPLY_FORM_HOME_SCREEN;
  static const WATER_APPLICATION_SEARCH = _Paths.WATER_APPLICATION_SEARCH;
  static const WATER_CONSUMER_SEARCH = _Paths.WATER_CONSUMER_SEARCH;
  static const TRADE_NEW_APPLICATION = _Paths.TRADE_NEW_APPLICATION;
  static const TRADE_RENEWAL = _Paths.TRADE_RENEWAL;
  static const TRADE_SURRENDER = _Paths.TRADE_SURRENDER;
  static const TRADE_AMENDMENT = _Paths.TRADE_AMENDMENT;
  static const TRADE_TRACK_LICENSE = _Paths.TRADE_TRACK_LICENSE;
  static const WATER_SITE_VERIFICATION = _Paths.WATER_SITE_VERIFICATION;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const PROPERTY_DAILY_TC_REPORT = _Paths.PROPERTY_DAILY_TC_REPORT;
  static const FAQ = _Paths.FAQ;
}

abstract class _Paths {
  _Paths._();
  static const LOGIN_SCREEN = '/login-screen';
  static const HOME = '/home';
  static const FIELD_VERIFICATION_PENDING_LIST = '/field-verification-pending-list';
  static const PROPERTY_HOME_SCREEN = '/property-home-screen';
  static const WATER_HOME_SCREEN = '/water-home-screen';
  static const TRADE_HOME_SCREEN = '/trade-home-screen';
  static const ADVERTISEMENT_HOME_SCREEN = '/advertisement-home-screen';
  static const PROPERTY_NEW_ASSESSMENT = '/property-new-assessment';
  static const PROPERTY_CONSESSION = '/property-consession';
  static const WATER_APPLY_CONNECTION = '/water-apply-connection';
  static const PROPERTY_MISSING_GEOTAGGING = '/property-missing-geotagging';
  static const PROPERTY_WATER_HARVESTING_FIELD_VERIFY = '/property-water-harvesting-field-verify';
  static const GEOTAGGING_VERIFY_FORM = '/geotagging-verify-form';
  static const PAYMENT = '/payment';
  static const PROPERTY_PAY_PROPERTY_TAX = '/property-pay-property-tax';
  static const HOME_ABOUT = '/home-about';
  static const PROPERTY_SEARCH_ASSESSMENT_DETAIL = '/property-search-assessment-detail';
  static const PROPERTY_REPORT = '/property-report';
  static const PROPERTY_GB_SAF_APPLY = '/property-gb-saf-apply';
  static const PROPERTY_CLUSTER = '/property-cluster';
  static const PROPERTY_GB_SAF_VERIFICATION = '/property-gb-saf-verification';
  static const SPLASH_SCREEN = '/splash-screen';
  static const PROPERTY_ADD_CLUSTER = '/property-add-cluster';
  static const PROPERTY_CONCESSION = '/property-concession';
  static const PROPERTY_APPLY_HARVESTING = '/property-apply-harvesting';
  static const PROPERTY_APPLY_FORM_HOME_SCREEN = '/property-apply-form-home-screen';
  static const WATER_APPLICATION_SEARCH = '/water-application-search';
  static const WATER_CONSUMER_SEARCH = '/water-consumer-search';
  static const TRADE_NEW_APPLICATION = '/trade-new-application';
  static const TRADE_RENEWAL = '/trade-renewal';
  static const TRADE_SURRENDER = '/trade-surrender';
  static const TRADE_AMENDMENT = '/trade-amendment';
  static const TRADE_TRACK_LICENSE = '/trade-track-license';
  static const WATER_SITE_VERIFICATION = '/water-site-verification';
  static const NOTIFICATION = '/notification';
  static const PROPERTY_DAILY_TC_REPORT = '/property-daily-tc-report';
  static const FAQ = '/faq';
}
